version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:                     
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ./includes/:/etc/nginx/includes/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - site1
      - site2
      - info
      - macusapi
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx
volumes:
  vhost:
  dhparam:
networks:
  site1:
    external:
      name: site1_default
  site2:
    external:
      name: site2_default
  info:                             
    external:                       
      name: info-line-bot_default   
  macusapi:                         
    external:                       
      name: macus-service_macus-api 
